site_name: RCPCH Digital Growth Charts Project Documentation

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    #  - navigation.tabs
    - navigation.tracking
    - navigation.top
    #  - toc.integrate

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  font:
    text: Montserrat
    code: Roboto Mono

  favicon: assets/dynamic-child-favicon.png
  logo: assets/logo-desktop.svg

plugins:
  - search
  - render_swagger

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - toc:
      permalink: true

copyright: Copyright &copy; 2021 Royal College of Paediatrics and Child Health (RCPCH)
repo_url: https://github.com/rcpch/digital-growth-charts-documentation

extra_css:
  - stylesheets/extra.css
